FROM confluentinc/cp-kafka:7.4.0

# Set environment variables for KRaft mode
ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES='broker,controller'
ENV KAFKA_LISTENERS='PLAINTEXT://:9092,CONTROLLER://:9093'
ENV KAFKA_ADVERTISED_LISTENERS='PLAINTEXT://localhost:9092'
ENV KAFKA_CONTROLLER_LISTENER_NAMES='CONTROLLER'
ENV KAFKA_CONTROLLER_QUORUM_VOTERS='1@localhost:9093'
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_JMX_PORT=9101
ENV KAFKA_JMX_HOSTNAME=localhost
ENV KAFKA_LOG_DIRS='/tmp/kraft-combined-logs'
ENV CLUSTER_ID='MkU3OEVBNTcwNTJENDM2Qk'

EXPOSE 9092 9101