spring:
  application:
    name: exchange
  profiles:
    active: local
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:exchange-order-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: order:org.vladpush.exchange.model.Order

server:
  port: 8080

exchange:
  kafka:
    topic:
      orders: order-events

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.vladpush.exchange: DEBUG